// // // export const allEnquiryFields = [
// // //     { id: "name", label: "Full Name", type: "text" },
// // //     { id: "email", label: "Email", type: "email" },
// // //     // { id: "name", label: "Name", type: "text", required: true },
// // //     // { id: "email", label: "Email", type: "email", required: true },
// // //     { id: "message", label: "Message", type: "textarea", required: false },
// // //     { id: "phone", label: "Mobile", type: "tel" },
// // //     { id: "streetAddress", label: "Street Address", type: "text" },
// // //     { id: "city", label: "City", type: "text" },
// // //     { id: "stateRegionProvince", label: "State/Region/Province", type: "text" },
// // //     { id: "postalZipCode", label: "Postal/Zip Code", type: "text" },
// // //     { id: "country", label: "Country", type: "select" },
// // //     { id: "gender", label: "Gender", type: "select" },
// // //     { id: "dateOfBirth", label: "Date of Birth", type: "date" },
// // //     { id: "studentType", label: "Student Type", type: "select" },
// // //     { id: "sscPercentage", label: "SSC Percentage", type: "number" },
// // //     { id: "schoolName", label: "School Name", type: "text" },
// // //     { id: "sscPassOutYear", label: "SSC Pass Out Year", type: "number" },
// // //     { id: "hscPercentage", label: "HSC Percentage", type: "number" },
// // //     { id: "juniorCollegeName", label: "Junior College Name", type: "text" },
// // //     { id: "hscPassOutYear", label: "HSC Pass Out Year", type: "number" },
// // //     { id: "graduationStream", label: "Graduation Stream", type: "select" },
// // //     { id: "graduationPercentage", label: "Graduation Percentage", type: "number" },
// // //     { id: "collegeName", label: "College Name", type: "text" },
// // //     { id: "graduationPassOutYear", label: "Graduation Pass Out Year", type: "number" },
// // //     { id: "postGraduationStream", label: "Post Graduation Stream", type: "text" },
// // //     { id: "postGraduationPercentage", label: "Post Graduation Percentage", type: "number" },
// // //     { id: "postGraduationCollegeName", label: "Post Graduation College Name", type: "text" },
// // //     { id: "postGraduationPassOutYear", label: "Post Graduation Pass Out Year", type: "number" },
// // //     { id: "branch", label: "Branch", type: "select" },
// // //     { id: "course", label: "Course", type: "select" },
// // //     { id: "source", label: "Source", type: "select" },
// // //     { id: "assignTo", label: "Assign To", type: "select" },
// // //     { id: "fee", label: "Fee", type: "number" },
// // //     { id: "degree", label: "Degree", type: "select" },
// // //     { id: "currentProfession", label: "Current Profession", type: "text" },
// // //     { id: "workingCompanyName", label: "Company Name", type: "text" },
// // //     { id: "workingDomain", label: "Working Domain", type: "text" },
// // //     { id: "experienceInYears", label: "Experience in Years", type: "number" },
// // //     { id: "guardianName", label: "Guardian Name", type: "text" },
// // //     { id: "guardianContact", label: "Guardian Contact", type: "tel" },
// // //     { id: "courseMotivation", label: "Course Motivation", type: "textarea" },
// // //     { id: "stage", label: "Stage", type: "select" },
// // //   ];


// // export const allEnquiryFields = [
// //   {
// //     category: "Personal Details",
// //     fields: [
// //       { id: "name", label: "Full Name", type: "text", required: true },
// //       { id: "email", label: "Email", type: "email", required: true },
// //       { id: "phone", label: "Mobile", type: "tel", required: true },
// //       { id: "streetAddress", label: "Street Address", type: "text" },
// //       { id: "city", label: "City", type: "text" },
// //       { id: "stateRegionProvince", label: "State/Region/Province", type: "text" },
// //       { id: "postalZipCode", label: "Postal/Zip Code", type: "text" },
// //       { id: "country", label: "Country", type: "select" },
// //       { id: "gender", label: "Gender", type: "select" },
// //       { id: "dateOfBirth", label: "Date of Birth", type: "date" },
// //       { id: "guardianName", label: "Guardian Name", type: "text" },
// //       { id: "guardianContact", label: "Guardian Contact", type: "tel" },
// //     ],
// //   },
// //   {
// //     category: "Additional Details",
// //     fields: [
// //       { id: "studentType", label: "Student Type", type: "select" },
// //       { id: "sscPercentage", label: "SSC Percentage", type: "number" },
// //       { id: "schoolName", label: "School Name", type: "text" },
// //       { id: "sscPassOutYear", label: "SSC Pass Out Year", type: "number" },
// //       { id: "hscPercentage", label: "HSC Percentage", type: "number" },
// //       { id: "juniorCollegeName", label: "Junior College Name", type: "text" },
// //       { id: "hscPassOutYear", label: "HSC Pass Out Year", type: "number" },
// //       { id: "graduationStream", label: "Graduation Stream", type: "select" },
// //       { id: "graduationPercentage", label: "Graduation Percentage", type: "number" },
// //       { id: "collegeName", label: "College Name", type: "text" },
// //       { id: "graduationPassOutYear", label: "Graduation Pass Out Year", type: "number" },
// //       { id: "postGraduationStream", label: "Post Graduation Stream", type: "text" },
// //       { id: "postGraduationPercentage", label: "Post Graduation Percentage", type: "number" },
// //       { id: "postGraduationCollegeName", label: "Post Graduation College Name", type: "text" },
// //       { id: "postGraduationPassOutYear", label: "Post Graduation Pass Out Year", type: "number" },
// //       { id: "currentProfession", label: "Current Profession", type: "text" },
// //       { id: "workingCompanyName", label: "Company Name", type: "text" },
// //       { id: "workingDomain", label: "Working Domain", type: "text" },
// //       { id: "experienceInYears", label: "Experience in Years", type: "number" },
// //     ],
// //   },
// //   {
// //     category: "Enquiry Details",
// //     fields: [
// //       { id: "message", label: "Message", type: "textarea", required: false },
// //       { id: "branch", label: "Branch", type: "select" },
// //       { id: "course", label: "Course", type: "select" },
// //       { id: "source", label: "Source", type: "select" },
// //       { id: "assignTo", label: "Assign To", type: "select" },
// //       { id: "fee", label: "Fee", type: "number" },
// //       { id: "degree", label: "Degree", type: "select" },
// //       { id: "courseMotivation", label: "Course Motivation", type: "textarea" },
// //       { id: "stage", label: "Stage", type: "select" },
// //     ],
// //   },
// // ];


// // export const allEnquiryFields = [
// //     { id: "name", label: "Full Name", type: "text" },
// //     { id: "email", label: "Email", type: "email" },
// //     // { id: "name", label: "Name", type: "text", required: true },
// //     // { id: "email", label: "Email", type: "email", required: true },
// //     { id: "message", label: "Message", type: "textarea", required: false },
// //     { id: "phone", label: "Mobile", type: "tel" },
// //     { id: "streetAddress", label: "Street Address", type: "text" },
// //     { id: "city", label: "City", type: "text" },
// //     { id: "stateRegionProvince", label: "State/Region/Province", type: "text" },
// //     { id: "postalZipCode", label: "Postal/Zip Code", type: "text" },
// //     { id: "country", label: "Country", type: "select" },
// //     { id: "gender", label: "Gender", type: "select" },
// //     { id: "dateOfBirth", label: "Date of Birth", type: "date" },
// //     { id: "studentType", label: "Student Type", type: "select" },
// //     { id: "sscPercentage", label: "SSC Percentage", type: "number" },
// //     { id: "schoolName", label: "School Name", type: "text" },
// //     { id: "sscPassOutYear", label: "SSC Pass Out Year", type: "number" },
// //     { id: "hscPercentage", label: "HSC Percentage", type: "number" },
// //     { id: "juniorCollegeName", label: "Junior College Name", type: "text" },
// //     { id: "hscPassOutYear", label: "HSC Pass Out Year", type: "number" },
// //     { id: "graduationStream", label: "Graduation Stream", type: "select" },
// //     { id: "graduationPercentage", label: "Graduation Percentage", type: "number" },
// //     { id: "collegeName", label: "College Name", type: "text" },
// //     { id: "graduationPassOutYear", label: "Graduation Pass Out Year", type: "number" },
// //     { id: "postGraduationStream", label: "Post Graduation Stream", type: "text" },
// //     { id: "postGraduationPercentage", label: "Post Graduation Percentage", type: "number" },
// //     { id: "postGraduationCollegeName", label: "Post Graduation College Name", type: "text" },
// //     { id: "postGraduationPassOutYear", label: "Post Graduation Pass Out Year", type: "number" },
// //     { id: "branch", label: "Branch", type: "select" },
// //     { id: "course", label: "Course", type: "select" },
// //     { id: "source", label: "Source", type: "select" },
// //     { id: "assignTo", label: "Assign To", type: "select" },
// //     { id: "fee", label: "Fee", type: "number" },
// //     { id: "degree", label: "Degree", type: "select" },
// //     { id: "currentProfession", label: "Current Profession", type: "text" },
// //     { id: "workingCompanyName", label: "Company Name", type: "text" },
// //     { id: "workingDomain", label: "Working Domain", type: "text" },
// //     { id: "experienceInYears", label: "Experience in Years", type: "number" },
// //     { id: "guardianName", label: "Guardian Name", type: "text" },
// //     { id: "guardianContact", label: "Guardian Contact", type: "tel" },
// //     { id: "courseMotivation", label: "Course Motivation", type: "textarea" },
// //     { id: "stage", label: "Stage", type: "select" },
// //   ];


// export const allEnquiryFields = [
//   {
//     category: "Personal Details",
//     fields: [
//       { id: "name", label: "Full Name", type: "text", required: true },
//       { id: "email", label: "Email", type: "email", required: true },
//       { id: "phone", label: "Mobile", type: "tel", required: true },
//       { id: "streetAddress", label: "Street Address", type: "text" },
//       { id: "city", label: "City", type: "text" },
//       { id: "stateRegionProvince", label: "State/Region/Province", type: "text" },
//       { id: "postalZipCode", label: "Postal/Zip Code", type: "text" },
//       { id: "country", label: "Country", type: "select" },
//       { id: "gender", label: "Gender", type: "select" },
//       { id: "dateOfBirth", label: "Date of Birth", type: "date" },
//       { id: "guardianName", label: "Guardian Name", type: "text" },
//       { id: "guardianContact", label: "Guardian Contact", type: "tel" },
//     ],
//   },
//   {
//     category: "Additional Details",
//     fields: [
//       { id: "studentType", label: "Student Type", type: "select" },
//       { id: "sscPercentage", label: "SSC Percentage", type: "number" },
//       { id: "schoolName", label: "School Name", type: "text" },
//       { id: "sscPassOutYear", label: "SSC Pass Out Year", type: "number" },
//       { id: "hscPercentage", label: "HSC Percentage", type: "number" },
//       { id: "juniorCollegeName", label: "Junior College Name", type: "text" },
//       { id: "hscPassOutYear", label: "HSC Pass Out Year", type: "number" },
//       { id: "graduationStream", label: "Graduation Stream", type: "select" },
//       { id: "graduationPercentage", label: "Graduation Percentage", type: "number" },
//       { id: "collegeName", label: "College Name", type: "text" },
//       { id: "graduationPassOutYear", label: "Graduation Pass Out Year", type: "number" },
//       { id: "postGraduationStream", label: "Post Graduation Stream", type: "text" },
//       { id: "postGraduationPercentage", label: "Post Graduation Percentage", type: "number" },
//       { id: "postGraduationCollegeName", label: "Post Graduation College Name", type: "text" },
//       { id: "postGraduationPassOutYear", label: "Post Graduation Pass Out Year", type: "number" },
//       { id: "currentProfession", label: "Current Profession", type: "text" },
//       { id: "workingCompanyName", label: "Company Name", type: "text" },
//       { id: "workingDomain", label: "Working Domain", type: "text" },
//       { id: "experienceInYears", label: "Experience in Years", type: "number" },
//     ],
//   },
//   {
//     category: "Enquiry Details",
//     fields: [
//       { id: "message", label: "Message", type: "textarea", required: false },
//       { id: "branch", label: "Branch", type: "select" },
//       { id: "course", label: "Course", type: "select" },
//       { id: "source", label: "Source", type: "select" },
//       { id: "assignTo", label: "Assign To", type: "select" },
//       { id: "fee", label: "Fee", type: "number" },
//       { id: "degree", label: "Degree", type: "select" },
//       { id: "courseMotivation", label: "Course Motivation", type: "textarea" },
//       {
//         id: "stage",
//         label: "Stage",
//         type: "select",
//         required: false,
//         options: ["prequalified", "qualified", "negotiation", "closed won", "closed lost", "contact in future"],
//       },
//       // { id: "stage", label: "Stage", type: "select" },
//       // { id: "stage", label: "Stage", options: ["prequalified", "qualified", "negotiation", "closed won", "closed lost", "contact in future"], },
//     ],
//   },
// ];


export const allEnquiryFields = [
  {
    category: "Personal Details",
    fields: [
      { id: "name", label: "Full Name", type: "text", required: true },
      { id: "email", label: "Email", type: "email", required: false },
      { id: "phone", label: "Mobile", type: "tel", required: false },
      { id: "streetAddress", label: "Street Address", type: "text", required: true },
      { id: "city", label: "City", type: "text", required: true },
      { id: "stateRegionProvince", label: "State/Region/Province", type: "text", required: true },
      { id: "postalZipCode", label: "Postal/Zip Code", type: "text", required: true },
      {
        id: "country",
        label: "Country",
        type: "select",
        options: ["", "India", "USA", "UK", "Canada", "Australia"],
      },
      {
        id: "gender",
        label: "Gender",
        type: "select",
        options: ["", "Female", "Male", "notToDisclose"],
      },
      { id: "dateOfBirth", label: "Date of Birth", type: "date" },
      { id: "guardianName", label: "Guardian Name", type: "text" },
      { id: "guardianContact", label: "Guardian Contact", type: "tel" },
      {
        id: "guardianRelation",
        label: "Guardian Relation",
        type: "select",
        options: ["", "Parent", "Sibling", "Spouse", "Other"],
      },
      { id: "createdBy", label: "Creator Name", type: "text", readOnly: true },
      { id: "owner", label: "Owner Name", type: "text", readOnly: true },
      { id: "lastModifiedTime", label: "Last Modified Time", type: "datetime", readOnly: true },
      { id: "lastTouched", label: "Last Touched", type: "datetime", readOnly: true },
    ],
  },
  {
    category: "Additional Details",
    fields: [
      {
        id: "studentType",
        label: "Student Type",
        type: "select",
        options: ["School Student", "College Student", "Fresher", "Working Professional"],
      },
      { id: "sscPercentage", label: "SSC Percentage", type: "number", min: 0, max: 100},
      { id: "schoolName", label: "School Name", type: "text" },
      // { id: "sscPassOutYear", label: "SSC Pass Out Year", type: "number", min: 1900, max: new Date().getFullYear() },
      // { id: "sscPassOutYear", label: "SSC Pass Out Year", type: "number", min: 1900, max: new Date().getFullYear() },
      { id: "sscPassOutYear", label: "SSC Pass Out Year", type: "number", min: 1990, max: new Date().getFullYear() },
      { id: "hscPercentage", label: "HSC Percentage", type: "number", min: 0, max: 100},
      { id: "juniorCollegeName", label: "Junior College Name", type: "text" },
      { id: "hscPassOutYear", label: "HSC Pass Out Year", type: "number", min: 1990, max: new Date().getFullYear() },
      // { id: "hscPassOutYear", label: "HSC Pass Out Year", type: "number", min: 1900, max: new Date().getFullYear() },
      {
        id: "highestDegree",
        label: "Highest Degree",
        type: "select",
        options: ["", "UG", "PG", "Doctorate"],
      },
      {
        id: "degree",
        label: "UG Degree",
        type: "select",
        options: [
          "",
          "BSc",
          "BCom",
          "BA",
          "BTech",
          "BCA",
          "BCCA",
          "B.Ed",
          "MBBS",
          "BDS",
          "B.Pham",
          "LLB",
          "BBA",
        ],
      },
      { id: "graduationBranch", label: "UG Branch", type: "text" },
      { id: "collegeName", label: "UG College", type: "text" },
      {
        id: "graduationPercentage",
        label: "UG Percentage",
        type: "number",
        min: 0,
        max: 100
      },
      { id: "graduationPassOutYear", label: "UG Pass Out Year", type: "number", min: 1990, max: new Date().getFullYear() },
      // {
      //   id: "graduationPassOutYear",
      //   label: "UG Pass Out Year",
      //   type: "number",
      //   min: 1900,
      //   max: new Date().getFullYear(),
      // },
      {
        id: "educationBreak",
        label: "Education Break",
        type: "select",
        options: ["", "No Break", "0 to 1 Years", "1 - 3 Years", "3 - 5 Years", "5+ Years"],
      },
      {
        id: "postGraduationDegree",
        label: "PG Degree",
        type: "select",
        options: ["MSc", "MBA", "MTech", "MCA", "MA", "MPhil", "MDes", "LLM"],
      },
      { id: "postGraduationBranch", label: "PG Branch", type: "text" },
      { id: "postGraduationCollegeName", label: "PG College", type: "text" },
      {
        id: "postGraduationPercentage",
        label: "PG Percentage",
        type: "number",
        min: 0,
        max: 100
      },
      { id: "postGraduationPassOutYear", label: "PG Pass Out Year", type: "number", min: 1990, max: new Date().getFullYear() },
      // {
      //   id: "postGraduationPassOutYear",
      //   label: "PG Pass Out Year",
      //   type: "number",
      //   min: 1900,
      //   max: new Date().getFullYear(),
      // },
      { id: "currentJobTitle", label: "Current Job Title", type: "text" },
      { id: "workingCompanyName", label: "Company Name", type: "text" },
      {
        id: "workingDomain",
        label: "Working Domain",
        type: "select",
        options: [
          "",
          "Banking and Finance",
          "Manufacturing",
          "Information Technology (IT) & Services",
          "Healthcare & Pharmaceuticals",
          "Education & EdTech",
          "Retail & E-commerce",
          "Telecommunications",
          "Logistics & Supply Chain",
          "Automotive",
          "Real Estate & Construction",
          "Media & Entertainment",
          "Hospitality & Tourism",
          "Energy & Utilities",
          "FMCG (Fast-Moving Consumer Goods)",
          "Agriculture & Agritech",
          "Legal & Professional Services",
          "Aerospace & Defense",
          "Government & Public Sector",
          "Insurance",
          "Non-Profit & NGOs",
        ],
      },
      {
        id: "experienceInYears",
        label: "Experience in Years",
        type: "select",
        options: [
          "",
          "Fresher",
          "0 to 1 Years",
          "1 - 3 Years",
          "3 - 5 Years",
          "5 - 10 Years",
          "10 - 15 Years",
          "15+ Years",
        ],
      },
      { id: "currentSalary", label: "Current Salary", type: "number", min: 0, step: 0.01 },
      {
        id: "workBreak",
        label: "Work Break",
        type: "select",
        options: ["", "No Break", "0 to 1 Years", "1 - 3 Years", "3 - 5 Years", "5+ Years"],
      },
    ],
  },
  {
    category: "Enquiry Details",
    fields: [
      { id: "branch", label: "Branch", type: "select" },
      {
        id: "course",
        label: "Course",
        type: "select",
      },
      {
        id: "source",
        label: "Source",
        type: "select",
        options: [
          "",
          "Instagram Ads",
          "Google Ads",
          "Referrals",
          "Google Search",
          "Emails",
          "Cold Calls",
          "Email Campaigns",
          "Blogs",
          "Webinar",
          "LinkedIn",
          "Events",
        ],
      },
      { id: "referredBy", label: "Referred By", type: "text" },
      { id: "assignTo", label: "Assign To", type: "select" },
      { id: "fee", label: "Fee", type: "number", min: 0, step: 0.01 },
      {
        id: "learningObjective",
        label: "Learning Objective",
        type: "select",
        options: [
          "",
          "none",
          "job transition",
          "career start",
          "ongoing job-upskill",
          "further education-upskill",
          "pursuing degree-upskill",
        ],
      },
      { id: "courseMotivation", label: "Course Motivation", type: "textarea" },
      {
        id: "stage",
        label: "Stage",
        type: "select",
        options: [
          "",
          "pre-qualified",
          "qualified",
          "negotiation",
          "closed-won",
          "closed-lost",
          "contact-in-future",
        ],
      },
      {
        id: "lostReason",
        label: "Lost Reason",
        type: "select",
        options: ["", "Price", "Location", "Schedule Conflict", "Not Interested", "Other"],
        required: false,
      },
      { id: "closingDate", label: "Closing Date", type: "date" },
      { id: "tags", label: "Tags", type: "select", multiple: true },
    ],
  },
];