// export const allEnquiryFields = [
//     { id: "name", label: "Full Name", type: "text" },
//     { id: "email", label: "Email", type: "email" },
//     // { id: "name", label: "Name", type: "text", required: true },
//     // { id: "email", label: "Email", type: "email", required: true },
//     { id: "message", label: "Message", type: "textarea", required: false },
//     { id: "phone", label: "Mobile", type: "tel" },
//     { id: "streetAddress", label: "Street Address", type: "text" },
//     { id: "city", label: "City", type: "text" },
//     { id: "stateRegionProvince", label: "State/Region/Province", type: "text" },
//     { id: "postalZipCode", label: "Postal/Zip Code", type: "text" },
//     { id: "country", label: "Country", type: "select" },
//     { id: "gender", label: "Gender", type: "select" },
//     { id: "dateOfBirth", label: "Date of Birth", type: "date" },
//     { id: "studentType", label: "Student Type", type: "select" },
//     { id: "sscPercentage", label: "SSC Percentage", type: "number" },
//     { id: "schoolName", label: "School Name", type: "text" },
//     { id: "sscPassOutYear", label: "SSC Pass Out Year", type: "number" },
//     { id: "hscPercentage", label: "HSC Percentage", type: "number" },
//     { id: "juniorCollegeName", label: "Junior College Name", type: "text" },
//     { id: "hscPassOutYear", label: "HSC Pass Out Year", type: "number" },
//     { id: "graduationStream", label: "Graduation Stream", type: "select" },
//     { id: "graduationPercentage", label: "Graduation Percentage", type: "number" },
//     { id: "collegeName", label: "College Name", type: "text" },
//     { id: "graduationPassOutYear", label: "Graduation Pass Out Year", type: "number" },
//     { id: "postGraduationStream", label: "Post Graduation Stream", type: "text" },
//     { id: "postGraduationPercentage", label: "Post Graduation Percentage", type: "number" },
//     { id: "postGraduationCollegeName", label: "Post Graduation College Name", type: "text" },
//     { id: "postGraduationPassOutYear", label: "Post Graduation Pass Out Year", type: "number" },
//     { id: "branch", label: "Branch", type: "select" },
//     { id: "course", label: "Course", type: "select" },
//     { id: "source", label: "Source", type: "select" },
//     { id: "assignTo", label: "Assign To", type: "select" },
//     { id: "fee", label: "Fee", type: "number" },
//     { id: "degree", label: "Degree", type: "select" },
//     { id: "currentProfession", label: "Current Profession", type: "text" },
//     { id: "workingCompanyName", label: "Company Name", type: "text" },
//     { id: "workingDomain", label: "Working Domain", type: "text" },
//     { id: "experienceInYears", label: "Experience in Years", type: "number" },
//     { id: "guardianName", label: "Guardian Name", type: "text" },
//     { id: "guardianContact", label: "Guardian Contact", type: "tel" },
//     { id: "courseMotivation", label: "Course Motivation", type: "textarea" },
//     { id: "stage", label: "Stage", type: "select" },
//   ];


export const allEnquiryFields = [
  {
    category: "Personal Details",
    fields: [
      { id: "name", label: "Full Name", type: "text", required: true },
      { id: "email", label: "Email", type: "email", required: true },
      { id: "phone", label: "Mobile", type: "tel", required: true },
      { id: "streetAddress", label: "Street Address", type: "text" },
      { id: "city", label: "City", type: "text" },
      { id: "stateRegionProvince", label: "State/Region/Province", type: "text" },
      { id: "postalZipCode", label: "Postal/Zip Code", type: "text" },
      { id: "country", label: "Country", type: "select" },
      { id: "gender", label: "Gender", type: "select" },
      { id: "dateOfBirth", label: "Date of Birth", type: "date" },
      { id: "guardianName", label: "Guardian Name", type: "text" },
      { id: "guardianContact", label: "Guardian Contact", type: "tel" },
    ],
  },
  {
    category: "Additional Details",
    fields: [
      { id: "studentType", label: "Student Type", type: "select" },
      { id: "sscPercentage", label: "SSC Percentage", type: "number" },
      { id: "schoolName", label: "School Name", type: "text" },
      { id: "sscPassOutYear", label: "SSC Pass Out Year", type: "number" },
      { id: "hscPercentage", label: "HSC Percentage", type: "number" },
      { id: "juniorCollegeName", label: "Junior College Name", type: "text" },
      { id: "hscPassOutYear", label: "HSC Pass Out Year", type: "number" },
      { id: "graduationStream", label: "Graduation Stream", type: "select" },
      { id: "graduationPercentage", label: "Graduation Percentage", type: "number" },
      { id: "collegeName", label: "College Name", type: "text" },
      { id: "graduationPassOutYear", label: "Graduation Pass Out Year", type: "number" },
      { id: "postGraduationStream", label: "Post Graduation Stream", type: "text" },
      { id: "postGraduationPercentage", label: "Post Graduation Percentage", type: "number" },
      { id: "postGraduationCollegeName", label: "Post Graduation College Name", type: "text" },
      { id: "postGraduationPassOutYear", label: "Post Graduation Pass Out Year", type: "number" },
      { id: "currentProfession", label: "Current Profession", type: "text" },
      { id: "workingCompanyName", label: "Company Name", type: "text" },
      { id: "workingDomain", label: "Working Domain", type: "text" },
      { id: "experienceInYears", label: "Experience in Years", type: "number" },
    ],
  },
  {
    category: "Enquiry Details",
    fields: [
      { id: "message", label: "Message", type: "textarea", required: false },
      { id: "branch", label: "Branch", type: "select" },
      { id: "course", label: "Course", type: "select" },
      { id: "source", label: "Source", type: "select" },
      { id: "assignTo", label: "Assign To", type: "select" },
      { id: "fee", label: "Fee", type: "number" },
      { id: "degree", label: "Degree", type: "select" },
      { id: "courseMotivation", label: "Course Motivation", type: "textarea" },
      { id: "stage", label: "Stage", type: "select" },
    ],
  },
];