export const OPEN_PASSWORD_MODAL = 'OPEN_PASSWORD_MODAL';
export const CLOSE_PASSWORD_MODAL = 'CLOSE_PASSWORD_MODAL';

export const OPEN_PROFILE_PANEL = 'OPEN_PROFILE_PANEL';
export const CLOSE_PROFILE_PANEL = 'CLOSE_PROFILE_PANEL';
